# Generated by Django 5.1.4 on 2025-01-14 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('hobbies', models.JSONField(default=list)),
            ],
        ),
    ]
